### ISSUE TITLE
Automation broken in AAX Wrapper

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vst3sdk#10]
There seems to be a severe issue with automations in the aaxwrapper of both the 3.6.8 and the 3.6.9 SDK when a plugin has more than one RangeParameter.

Here are the steps to reproduce for the SDK's again_aax sample (found in ProTools 12.6 on both Mac OS and Windows, but it can likely be reproduced with other versions, too. The used AAX SDK version is 2.3.0):

1. Add e.g. two dummy RangeParameters in AGainController::initialize():
parameters.addParameter(STR16("Idk"), 0, 0, 0, ParameterInfo::kCanAutomate, 'bleh');
parameters.addParameter(STR16("Idk2"), 0, 0, 0, ParameterInfo::kCanAutomate, 'blah');
2. Patch again.uidesc accordingly to expose two additional sliders.
3. Build again_aax and copy it to the AAX Plugin directory.
4. Start ProTools, create and empty session, add a strereo track.
5. Instanciate again_aax.
6. Add the gain parameter to the automation list.
7. Put automation into write mode and start playback.
8. Move the gain slider around.

-> No automation is written.

It affects seemingly random (but always the same set of) parameters if you have more then one RangeParameters.

**Comment by raygit83** [comment]
This seems to be related to https://github.com/steinbergmedia/vst3sdk/issues/12
I also see there's stuff that's commented in AAXWrapper_Parameters::SetParameterNormalizedValue() and AAXWrapper_Parameters::UpdateParameterNormalizedValue(). Any hints why?

**Comment by raygit83** [comment]
Parts of it are addressed by this PR https://github.com/steinbergmedia/vst3_public_sdk/pull/5 but there are still some issues left with discrete parameters.

**Comment by ygrabit** [comment]
will be fixed in next SDK update
