### ISSUE TITLE
AUCocoaView is broken in cases where the same auwrapper lib is used in different plugs (SDK v3.7.7)

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vst3sdk#108]
See here:

https://forums.steinberg.net/t/aucocoaview-wrapper-is-broken-when-the-same-auwrapper-lib-is-used-in-different-plugs-sdk-v3-7-7

**Comment by raygit83** [comment]
Here's a patch: https://github.com/raygit83/vst3_public_sdk

**Comment by ygrabit** [comment]
will be fixed in 3.7.8
