### ISSUE TITLE
Controller CID output from validator cut on non Windows platform

### ISSUE THREAD

**Issue by xoofx** [steinbergmedia/vst3sdk#109]
Hey,

I'm using the validator to implement unit tests and I do a text diff in my unit tests with a verified snapshot, and I found that 3.7.7 brought a regression in the output of the validator for the Controller CID that is cut by 3 chars (2 hex digits + the trailing `}`)

This is an extract output of the build of the SDK on Linux for example:

```
[Scan Editor Classes]
Info:  ===Scan Editor Classes ====================================
Info:  This component has an edit controller class
Info:     Controller CID: {9F34E8E9-22FC-42E6-993C-6007642512
[Succeeded]
```

See above `Controller CID: {9F34E8E9-22FC-42E6-993C-6007642512` is missing 2 hex digits + the trailing `}`.

I haven't spotted anything suspicious in the code diff for 3.7.7, so not sure what is happening but there is something weird...

**Comment by ygrabit** [comment]
Thanks for the report, this will be fixed in the next update of the SDK
