### ISSUE TITLE
Bypass simulation logic still broken in AAX Wrapper

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vst3sdk#11]
The AAX Wrapper exposes an additional parameter named "Bypass" additionally to a "Master Bypass" provided by an underlying VST3 implementation that is flagged as ParameterInfo::kIsBypass.

A bypass parameter should only be simulated if the VST3 does not expose a bypass parameter at all, hence the condition:

mSimulateBypass = (mWrapper->mBypassParameterID != Vst::kNoParamId);

in the AAXWrapper_Parameters ctor should be inverted to 

mSimulateBypass = (mWrapper->mBypassParameterID == Vst::kNoParamId);

However, doing so stops the existing VST3 bypass parameter from working, so it seems there's more logic depending on mSimulateBypass that's broken.

**Comment by ygrabit** [comment]
i will recheck this...Thx

**Comment by raygit83** [comment]
This is addressed in the following PR https://github.com/steinbergmedia/vst3_public_sdk/pull/5

**Comment by ygrabit** [comment]
will be fixed in next SDK update...
