### ISSUE TITLE
Crash in AUv2 Wrapper using VST3 SDK v3.7.7

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vst3sdk#110]
See here: https://forums.steinberg.net/t/crash-in-auv2-wrapper-using-vst3-sdk-v3-7-7/838542

**Comment by scheffle** [comment]
Will be fixed with the next SDK update.

**Comment by raygit83** [comment]
Okay, that's great news. Out of curiosity: Any hints on how you fixed this? Can I review the respective commit somewhere? Thanks.
