### ISSUE TITLE
Does the BaseWrapper::processMidiEvent function have a bug?

### ISSUE THREAD

**Issue by simpleway2016** [steinbergmedia/vst3sdk#114]
The BaseWrapper::processMidiEvent cannot handle the sustain pedal signal of MIDI. I am using the VST3 version of Kontakt, but stepping on the sustain pedal is not having any effect. Does this mean there is a bug in the processMidiEvent function?

**Comment by ygrabit** [comment]
You should report this problem to Native Instrument... VST3 SDK works with Sustain pedal by mapping MIDI CC (64) to a dedicated parameter. If Kontakt does not have this parameter, SustainPedal is not supported.

**Comment by simpleway2016** [comment]
> You should report this problem to Native Instrument... VST3 SDK works with Sustain pedal by mapping MIDI CC (64) to a dedicated parameter. If Kontakt does not have this parameter, SustainPedal is not supported.

If it is an issue with the VST3 plugin itself, then why is it that in DAW software like Cubase, using the same VST3 plugin, the sustain pedal is effective?

**Comment by simpleway2016** [comment]
> > You should report this problem to Native Instrument... VST3 SDK works with Sustain pedal by mapping MIDI CC (64) to a dedicated parameter. If Kontakt does not have this parameter, SustainPedal is not supported.
> 
> If it is an issue with the VST3 plugin itself, then why is it that in DAW software like Cubase, using the same VST3 plugin, the sustain pedal is effective?

And furthermore, the VST2 version of the same plugin, which passes all received MIDI signals to the plugin, also has an effective sustain pedal.
