### ISSUE TITLE
How to install though?

### ISSUE THREAD

**Issue by jiapei100** [steinbergmedia/vst3sdk#117]
The code has been successfully built, via **cmake**. However, There seems to be **NO install** in `CMakeLists.txt`. Can How can I install **vst3sdk** by command line?

```console
➜  build git:(master) ✗ sudo make install
[sudo] password for XXXXXXXX: 
make: *** No rule to make target 'install'.  Stop.
```

**Comment by ygrabit** [comment]
There is no plan to provide such possibility...
