### ISSUE TITLE
Inconsistency between docs & code for module initializer / deinitializer names

### ISSUE THREAD

**Issue by jcelerier** [steinbergmedia/vst3sdk#119]
In the docs:

https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/VST+Module+Architecture/Index.html

> On macOS the entry/exit functions are named BundleEntry / BundleExit and are required!

In the code:  

https://github.com/steinbergmedia/vst3_public_sdk/blob/e61ee76eb0f8771a05e99018bc4705ac1b603e48/source/main/macmain.cpp

```

//------------------------------------------------------------------------
bool InitModule (); ///< must be provided by plug-in: called when the library is loaded
bool DeinitModule (); ///< must be provided by plug-in: called when the library is unloaded

//------------------------------------------------------------------------
extern "C" {
/** bundleEntry and bundleExit must be provided by the plug-in! */
SMTG_EXPORT_SYMBOL bool bundleEntry (CFBundleRef);
SMTG_EXPORT_SYMBOL bool bundleExit (void);
}
```

Which one is it supposed to be? `BundleEntry` or `bundleEntry` ?

**Comment by ygrabit** [comment]
bundleEntry and bundleExit are the right ones.
thanks for finding the error in the doc, I will fix it.
