### ISSUE TITLE
Automation list is wrong in AAX Wrapper

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vst3sdk#12]
The wrong set of parameters is added in AAXWrapper_Parameters::EffectInit() (see screenshot). 
You can see the faulty extra Bypass parameter described in https://github.com/steinbergmedia/vst3sdk/issues/11.
Besides that the "Wet Mix" and "Level" parameters are missing, although they are marked as automatable and they are correctly exposed in VST2, VST3 and AU.

I have also inspected the loop that sets up mParameterMap in Vst2Wrapper::setupParameters() which correctly iterates the expected parameters. The loop in AAXWrapper_Parameters::EffectInit(), however then finds and adds the wrong set of parameters that can also be seen in the screenshot.

![bucket](https://user-images.githubusercontent.com/22492388/37090710-ad717212-2205-11e8-8e66-bc14bdd1a429.PNG)

**Comment by raygit83** [comment]
This is addressed in the following PR https://github.com/steinbergmedia/vst3_public_sdk/pull/5

**Comment by ygrabit** [comment]
will be fixed in next update
