### ISSUE TITLE
Cannot git clone project

### ISSUE THREAD

**Issue by etheory** [steinbergmedia/vst3sdk#124]
Following the readme instructions no longer works, I get the following message before the repo fails to clone:

`error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 6234 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/steinbergmedia/vst3_doc' into submodule path 'D:/Programming/audio/vst3sdk/doc' failed
Failed to clone 'doc' a second time, aborting
`

Could someone please look into this?

I'm on Windows 10, using tortoisegit or git from the command line, never had this issue before.

(edit: bizarrely it seems to work from github desktop when done via the gui, but not via command-line....)

**Comment by ygrabit** [comment]
Did you succeed here?

**Comment by etheory** [comment]
Thanks @ygrabit I did in the end, but it ONLY worked using github desktop. Using a command-line github it still refuses to work, and I'm not sure why.

**Comment by ygrabit** [comment]
very strange...
