### ISSUE TITLE
Would you like add some description about when&where to sign a  non-free version agreement?

### ISSUE THREAD

**Issue by Huayuluoshi** [steinbergmedia/vst3sdk#127]
Hello!
As title goes,I couldn't find some information about that.So,witch situation should I sign the non-free version agreement?
Now I have a question.I start a project,but it is only build for open sourced vst3 plug-ins,and distribute the binary for public.I do not make any of plug-ins.So,witch agreement should I sign?
Thank you for your help!

**Comment by ygrabit** [comment]
Hi
did you check this:[FAQ License](https://steinbergmedia.github.io/vst3_dev_portal/pages/FAQ/Licensing.html#q-i-would-like-to-distribute-my-vst-3-plug-inhost-in-binary-form-which-is-based-on-a-3rd-party-sdk-like-juce-and-used-its-gplv3-license)?

**Comment by Huayuluoshi** [comment]
> Hi did you check this:[FAQ License](https://steinbergmedia.github.io/vst3_dev_portal/pages/FAQ/Licensing.html#q-i-would-like-to-distribute-my-vst-3-plug-inhost-in-binary-form-which-is-based-on-a-3rd-party-sdk-like-juce-and-used-its-gplv3-license)?

Thanks！
