### ISSUE TITLE
Initial latency isn't reported in AAX Wrapper

### ISSUE THREAD

**Issue by raygit83** [steinbergmedia/vst3sdk#13]
I suggest adding "ctrl->SetSignalLatency(mWrapper->mProcessor->getLatencySamples());" in AAXWrapper_Parameters::EffectInit() below line 135.

**Comment by ygrabit** [comment]
i will check this. Thx

**Comment by raygit83** [comment]
This is addressed in the following PR https://github.com/steinbergmedia/vst3_public_sdk/pull/5

**Comment by ygrabit** [comment]
will be fixed in next SDK update...
