### ISSUE TITLE
Configuring incomplete, errors occurred! (Ubuntu 17.10)

### ISSUE THREAD

**Issue by hexxamillion** [steinbergmedia/vst3sdk#14]
I received the errors below. I assume it has to do with freetype package. I installed freetype2. I still get this error. A list of the prerequisites would be helpful for LINUX installations.

CMake Error at /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.9/Modules/FindFreetype.cmake:140 (find_package_handle_standard_args)
  vstgui4/vstgui/CMakeLists.txt:70 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by rehans** [comment]
Hey,

I am using Ubuntu 17.10 and CMake 3.9.1. In the SDK documentation it says:
`1. Required: sudo apt-get install cmake gcc "libstdc++6" libgtkmm-3.0-dev`

While cmake is generating:
`-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.0") `

I cannot remember that I installed the Freetype manually though.

**Comment by mfisher31** [comment]
@hexxamillion - try installing this package if you haven't already

```libfreetype6-dev```

**Comment by hexxamillion** [comment]
Cool. I will try that.

**Comment by hexxamillion** [comment]
@mfisher31 I already had that package installed apparently. However it looks like I was missing some other ones that @rehans suggested.

**Comment by hexxamillion** [comment]
Thx for everyone's help. It successfully compiled now. I had the freetype package already but I did not know about these other prereqs: "libstdc++6" libgtkmm-3.0-dev.

**Comment by mfisher31** [comment]
good, glad to hear it.  personally I think it would be nice if this project used autotools (or even better waf) to automatically check requirements when running configure.

**Comment by scheffle** [comment]
It's all in the documentation ;-)
