### ISSUE TITLE
Wrong information on the wiki

### ISSUE THREAD

**Issue by temrix** [steinbergmedia/vst3sdk#2]
This is what is currently in the wiki:
```
git pull https://github.com/steinbergmedia/vst3sdk.git
cd vst3sdk
git submodules init
git submodules update
```
I’m still a bit of a noob with git but shouldn't this be _clone_ instead of _pull_?
Also ~~``git submodules``~~ is a typo. It should be ``git submodule`` instead.

**Comment by rehans** [comment]
Yes, that's true.

You can also do
<code>
git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
</code>

Like this everything is initialised in one step.

**Comment by ygrabit** [comment]
text updated
