### ISSUE TITLE
confusion - where are the files?

### ISSUE THREAD

**Issue by esaruoho** [steinbergmedia/vst3sdk#23]
I'm thoroughly confused. I'm looking around this repo, and can't click on `pluginterfaces` or `public.sdk` at https://github.com/steinbergmedia/vst3sdk.

if i clone the repo, those folders exist, but they contain nothing.

what am i missing?

**Comment by aclex** [comment]
@esaruoho these look like submodules, so you probably want to do `git submodule update --init --recursive` in the repository root to fill them.

**Comment by scheffle** [comment]
See https://github.com/steinbergmedia/vst3sdk/wiki/Get-Started .
