### ISSUE TITLE
Required files missing dual license

### ISSUE THREAD

**Issue by ssj71** [steinbergmedia/vst3sdk#3]
It appears the license file in the top directory expressly states that it only applies to files that reference it. (see https://github.com/steinbergmedia/vst3sdk/blob/master/LICENSE.txt#L5 )
However it seems that many files required to compile a plugin do not reference the license and show they are still under the custom Steinberg license. From what I can see all files in public.sdk/source/ are in this scenario and they are required for building a plugin. I believe this means no vst can be made gpl compatible using the SDK since some of the code that gets compiled into the binary is not covered by the dual license. 

Hopefully its just a mistake and these files' headers can be edited to include the dual licensing.
Thanks. Its very exciting to see Steinberg working toward supporting the GPL.

**Comment by scheffle** [comment]
The files in public.sdk are licensed under the BSD style license. Only the files in pluginterfaces are dual licensed (GPL and custom Steinberg license).

**Comment by x42** [comment]
The problem is that it's a 3-clause BSD-style license (no advertisement clause) that is not GPL compatible. 

So the SDK can only be used along with the plugin-interfaces if one uses Steinberg's custom license.

**Comment by scheffle** [comment]
https://www.gnu.org/licenses/license-list.html#ModifiedBSD

According to gnu.org it is compatible.

**Comment by x42** [comment]
Thanks for the clarification.  The "advertisement" vs "no-endoresement" clauses is what caused confusion on my part. so GPLv3 it is. Cheers!
