### ISSUE TITLE
Build failure on Linux if $TARGET_DESTINATION does not exist

### ISSUE THREAD

**Issue by ferdnyc** [steinbergmedia/vst3sdk#31]
I encountered a build failure on Fedora 29 after the first plugin (adelay) passed its TestSuite run, when the build process attempted to link it into `${TARGET_DESTINATION}` (which is `${HOME}/.vst3/` by default), without first ensuring that the directory exists.

PR steinbergmedia/vst3_cmake#1 addresses this issue, by adding a `mkdir -p "${TARGET_DESTINATION}"` prior to the `ln -sfF` command.

**Comment by ferdnyc** [comment]
Closed via steinbergmedia/vst3_cmake#1 .

**Comment by dspreadbury** [comment]
Hi all,

Can we do the necessary button-pushing to get Dorico 2.2.20 released at 12pm Hamburg time?

11.55 – Sladjan/Merlin puts SDA live
11.55 – Georg/Ed puts support page live
12.00 – Guillermo announces on @steinbergmedia<mailto:reply@reply.github.com>
12.00 – Daniel announces on forum
12.00 – Daniel publishes blog post
12.00 – Daniel announces on @doricoofficial

All sound OK?

Thanks!

Daniel

Product Marketing Manager
Phone: +44 20 3696 1811

Steinberg Media Technologies GmbH
Beim Strohhause 31, 20097 Hamburg, Germany

President: Andreas Stelling | Managing Directors: Thomas Schöpe, Yoshiyuki Tsugawa
Registration Court: Hamburg HR B 86 534 | VAT ID: DE118677139

Visit the Steinberg website<http://www.steinberg.net> or connect with us on Facebook<http://www.facebook.com/Steinberg>, Twitter<http://twitter.com/steinbergmedia>, Instagram<http://www.instagram.com/steinbergmedia> and SoundCloud<http://www.soundcloud.com/steinbergmedia>.
Watch our Cubase<https://www.youtube.com/cubase>, Dorico<https://www.youtube.com/dorico>, Mobile Apps<https://www.youtube.com/mobile_apps_steinberg>, Nuendo<https://www.youtube.com/nuendo>, Steinberg<https://www.youtube.com/user/SteinbergSoftware>, Audio Interfaces<https://www.youtube.com/audiointerfaces>, VST Instruments & Plug-Ins<https://www.youtube.com/VSTinstrumentsplugins> and WaveLab<https://www.youtube.com/WaveLab> videos on YouTube.

**Comment by dspreadbury** [comment]
Hi all,

Dorico 2.2.20 is now announced on the Dorico forum, the blog post is live, and it has also been announced via the @doricoofficial social channels.

Thanks,

Daniel

From: Sladjan Matkovic <s.matkovic@steinberg.de>
Date: Wednesday, 24 April 2019 at 10:55
To: Daniel Spreadbury <D.Spreadbury@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Guillermo Navarrete <G.Navarrete@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Re: Dorico 2.2.20 live at 12pm Hamburg time?

Hi everyone,

Dorico 2.2.0 is now available via SDA.

Best regards,
Sladjan

From: Daniel Spreadbury <D.Spreadbury@steinberg.de>
Date: Wednesday, 24. April 2019 at 10:47
To: Sladjan Matkovic <s.matkovic@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Guillermo Navarrete <G.Navarrete@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Dorico 2.2.20 live at 12pm Hamburg time?

Hi all,

Can we do the necessary button-pushing to get Dorico 2.2.20 released at 12pm Hamburg time?

11.55 – Sladjan/Merlin puts SDA live
11.55 – Georg/Ed puts support page live
12.00 – Guillermo announces on @steinbergmedia<mailto:reply@reply.github.com>
12.00 – Daniel announces on forum
12.00 – Daniel publishes blog post
12.00 – Daniel announces on @doricoofficial

All sound OK?

Thanks!

Daniel

Product Marketing Manager
Phone: +44 20 3696 1811

Steinberg Media Technologies GmbH
Beim Strohhause 31, 20097 Hamburg, Germany

President: Andreas Stelling | Managing Directors: Thomas Schöpe, Yoshiyuki Tsugawa
Registration Court: Hamburg HR B 86 534 | VAT ID: DE118677139

Visit the Steinberg website<http://www.steinberg.net> or connect with us on Facebook<http://www.facebook.com/Steinberg>, Twitter<http://twitter.com/steinbergmedia>, Instagram<http://www.instagram.com/steinbergmedia> and SoundCloud<http://www.soundcloud.com/steinbergmedia>.
Watch our Cubase<https://www.youtube.com/cubase>, Dorico<https://www.youtube.com/dorico>, Mobile Apps<https://www.youtube.com/mobile_apps_steinberg>, Nuendo<https://www.youtube.com/nuendo>, Steinberg<https://www.youtube.com/user/SteinbergSoftware>, Audio Interfaces<https://www.youtube.com/audiointerfaces>, VST Instruments & Plug-Ins<https://www.youtube.com/VSTinstrumentsplugins> and WaveLab<https://www.youtube.com/WaveLab> videos on YouTube.

**Comment by dspreadbury** [comment]
Hi,

We have just posted it at the Steinberg Facebook and Twitter accounts.

Best regards,
Guillermo Navarrete

From: Daniel Spreadbury <D.Spreadbury@steinberg.de>
Date: Wednesday, 24. April 2019 at 12:05
To: Sladjan Matkovic <s.matkovic@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Guillermo Navarrete <G.Navarrete@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Re: Dorico 2.2.20 live at 12pm Hamburg time?

Hi all,

Dorico 2.2.20 is now announced on the Dorico forum, the blog post is live, and it has also been announced via the @doricoofficial social channels.

Thanks,

Daniel

From: Sladjan Matkovic <s.matkovic@steinberg.de>
Date: Wednesday, 24 April 2019 at 10:55
To: Daniel Spreadbury <D.Spreadbury@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Guillermo Navarrete <G.Navarrete@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Re: Dorico 2.2.20 live at 12pm Hamburg time?

Hi everyone,

Dorico 2.2.0 is now available via SDA.

Best regards,
Sladjan

From: Daniel Spreadbury <D.Spreadbury@steinberg.de>
Date: Wednesday, 24. April 2019 at 10:47
To: Sladjan Matkovic <s.matkovic@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Guillermo Navarrete <G.Navarrete@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Dorico 2.2.20 live at 12pm Hamburg time?

Hi all,

Can we do the necessary button-pushing to get Dorico 2.2.20 released at 12pm Hamburg time?

11.55 – Sladjan/Merlin puts SDA live
11.55 – Georg/Ed puts support page live
12.00 – Guillermo announces on @steinbergmedia<mailto:reply@reply.github.com>
12.00 – Daniel announces on forum
12.00 – Daniel publishes blog post
12.00 – Daniel announces on @doricoofficial

All sound OK?

Thanks!

Daniel

Social Media Manager
Phone: +49 40 21035 267 | Mobile: +49 172 323 5190

Steinberg Media Technologies GmbH
Beim Strohhause 31, 20097 Hamburg, Germany

President: Andreas Stelling | Managing Directors: Thomas Schöpe, Yoshiyuki Tsugawa
Registration Court: Hamburg HR B 86 534 | VAT ID: DE118677139

Visit the Steinberg website<http://www.steinberg.net> or connect with us on Facebook<http://www.facebook.com/Steinberg>, Twitter<http://twitter.com/steinbergmedia>, Instagram<http://www.instagram.com/steinbergmedia> and SoundCloud<http://www.soundcloud.com/steinbergmedia>.
Watch our Cubase<https://www.youtube.com/cubase>, Dorico<https://www.youtube.com/dorico>, Mobile Apps<https://www.youtube.com/mobile_apps_steinberg>, Nuendo<https://www.youtube.com/nuendo>, Steinberg<https://www.youtube.com/user/SteinbergSoftware>, Audio Interfaces<https://www.youtube.com/audiointerfaces>, VST Instruments & Plug-Ins<https://www.youtube.com/VSTinstrumentsplugins> and WaveLab<https://www.youtube.com/WaveLab> videos on YouTube.

**Comment by dspreadbury** [comment]
Hi everyone,

The download page certainly has been updated, too.

Cheers,

Georg

From: Guillermo Navarrete <G.Navarrete@steinberg.de>
Date: Wednesday, 24. April 2019 at 12:07
To: Daniel Spreadbury <D.Spreadbury@steinberg.de>, Sladjan Matkovic <s.matkovic@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Re: Dorico 2.2.20 live at 12pm Hamburg time?

Hi,

We have just posted it at the Steinberg Facebook and Twitter accounts.

Best regards,
Guillermo Navarrete

From: Daniel Spreadbury <D.Spreadbury@steinberg.de>
Date: Wednesday, 24. April 2019 at 12:05
To: Sladjan Matkovic <s.matkovic@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Guillermo Navarrete <G.Navarrete@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Re: Dorico 2.2.20 live at 12pm Hamburg time?

Hi all,

Dorico 2.2.20 is now announced on the Dorico forum, the blog post is live, and it has also been announced via the @doricoofficial social channels.

Thanks,

Daniel

From: Sladjan Matkovic <s.matkovic@steinberg.de>
Date: Wednesday, 24 April 2019 at 10:55
To: Daniel Spreadbury <D.Spreadbury@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Guillermo Navarrete <G.Navarrete@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Re: Dorico 2.2.20 live at 12pm Hamburg time?

Hi everyone,

Dorico 2.2.0 is now available via SDA.

Best regards,
Sladjan

From: Daniel Spreadbury <D.Spreadbury@steinberg.de>
Date: Wednesday, 24. April 2019 at 10:47
To: Sladjan Matkovic <s.matkovic@steinberg.de>, Merlin Thomas <m.thomas@steinberg.de>, Guillermo Navarrete <G.Navarrete@steinberg.de>, Georg Kiria <G.Kiria@steinberg.de>, Eckhard Doll <E.Doll@steinberg.de>, steinbergmedia/vst3sdk <reply@reply.github.com>
Subject: Dorico 2.2.20 live at 12pm Hamburg time?

Hi all,

Can we do the necessary button-pushing to get Dorico 2.2.20 released at 12pm Hamburg time?

11.55 – Sladjan/Merlin puts SDA live
11.55 – Georg/Ed puts support page live
12.00 – Guillermo announces on @steinbergmedia<mailto:reply@reply.github.com>
12.00 – Daniel announces on forum
12.00 – Daniel publishes blog post
12.00 – Daniel announces on @doricoofficial

All sound OK?

Thanks!

Daniel

Content Editor Technical Support
Phone: +49 40 21035 276

Steinberg Media Technologies GmbH
Beim Strohhause 31, 20097 Hamburg, Germany

President: Andreas Stelling | Managing Directors: Thomas Schöpe, Yoshiyuki Tsugawa
Registration Court: Hamburg HR B 86 534 | VAT ID: DE118677139

Visit the Steinberg website<http://www.steinberg.net> or connect with us on Facebook<http://www.facebook.com/Steinberg>, Twitter<http://twitter.com/steinbergmedia>, Instagram<http://www.instagram.com/steinbergmedia> and SoundCloud<http://www.soundcloud.com/steinbergmedia>.
Watch our Cubase<https://www.youtube.com/cubase>, Dorico<https://www.youtube.com/dorico>, Mobile Apps<https://www.youtube.com/mobile_apps_steinberg>, Nuendo<https://www.youtube.com/nuendo>, Steinberg<https://www.youtube.com/user/SteinbergSoftware>, Audio Interfaces<https://www.youtube.com/audiointerfaces>, VST Instruments & Plug-Ins<https://www.youtube.com/VSTinstrumentsplugins> and WaveLab<https://www.youtube.com/WaveLab> videos on YouTube.
