### ISSUE TITLE
Build fails when SMTG_COREAUDIO_SDK_PATH was set

### ISSUE THREAD

**Issue by moutend** [steinbergmedia/vst3sdk#33]
### Environment

- Mac OSX 10.14.3
- Xcode 10.1
- latest version of vst3sdk (commit 82380a)

### What did you do?

I did the following steps to build the sample VST3 plugins.

```console
git clone --recursive https://github.com/steinbergmedia/vst3sdk.git
mkdir ./build
cd ./build
cmake -GXcode ../vst3sdk
xcodebuild
```

The `xcodebuild` was finished without any errors. This is the expected behavior.

### Problem

The `xcodebuild` produces file not found error when the Audio Unit support enabled.

According to the `vst3sdk/cmake/modules/CoreAudioSupport.cmake`, the CoreAudio SDK path is next to the vst3sdk, the SMTG_COREAUDIO_SDK_PATH will be automatically detected.

So I did the following steps:

```console
mkdir -p ../CoreAudio/AudioUnits
cp -r ~/Downloads/AudioUnitExamplesAudioUnitEffectGeneratorInstrumentMIDIProcessorandOffline/* ../CoreAudio/AudioUnits
cmake -GXcode ../vst3sdk
xcodebuild
```

Then I got the file not found error like this.

```console
$ cmake -GXcode ../vst3sdk
-- Building with Xcode version: 10.1
-- macOS Deployment Target: 10.10
-- SMTG_MYPLUGINS_SRC_PATH is not set. If you want to add your own plug-ins folder, specify it!
-- SMTG_COREAUDIO_SDK_PATH is set to : /Users/koyanagi/develop/vst3sdk/../CoreAudio
-- SMTG_AAX_SDK_PATH is not set. If you need it, please download the AAX SDK!
* To enable building the InterAppAudio NoteExpressionSynth example for iOS you need to set the SMTG_IOS_DEVELOPMENT_TEAM and use the Xcode generator
* To enable building the AUv3 Wrapper example for iOS you need to set the SMTG_IOS_DEVELOPMENT_TEAM and use the Xcode generator
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/koyanagi/develop/build
$ xcodebuild
...
/Users/koyanagi/develop/vst3sdk/public.sdk/source/vst/auwrapper/ausdk.mm:49:9: fatal error:
      'PublicUtility/CABundleLocker.cpp'
      file not found
#import "PublicUtility/CABundleLocker.cpp"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

It seems to be not proper version of the CoreAudio SDK.

### Question

Where can I get the proper version of the CoreAudio SDK?

FYI, I use the latest CoreAudio SDK which downloaded from

https://developer.apple.com/library/archive/samplecode/sc2195/Introduction/Intro.html

**Comment by scheffle** [comment]
Hi,
please use Version 1.1 of the CoreAudioSDK (or Core Audio Utility Classes) for now: https://developer.apple.com/library/archive/samplecode/CoreAudioUtilityClasses/Introduction/Intro.html

**Comment by moutend** [comment]
@scheffle I've downloaded the SDK, and the all builds succeeds. Thanks!
