### ISSUE TITLE
audiohost is not built by default

### ISSUE THREAD

**Issue by fpesari** [steinbergmedia/vst3sdk#38]
I compiled the latest version of the VST3 SDK and by default it does not build the `audiohost` program, while it builds `editorhost`.

**Comment by scheffle** [comment]
Can you be more specific on which system you are? Thanks.

**Comment by scheffle** [comment]
Closing due to no feedback.

**Comment by fpesari** [comment]
Apologies, I am on openSUSE Leap.

**Comment by ergodaveh** [comment]
AFIK ...using my efforts to build the audiohost.  The Jack Audio Sdk must be installed/registered prior to building the ah.
