### ISSUE TITLE
[Linux] Compiled VST plugins are not detected by any DAW

### ISSUE THREAD

**Issue by NoxWings** [steinbergmedia/vst3sdk#40]
I've downloaded the SDK `vstsdk3613_08_04_2019_build_81.zip` file.

I'm running Debian Stable and all samples seem to compile fine. I've moved all the .so generated to my `~/.vst` folder including all the samples like adelay.

I've tried to see if I could get the plugins to show up on Ardour, LMMS with Carla host and Helio.fm. All of them are supposed to be able to load linux VST3 plugins. The only other linux VST plugin I have to compare is Tunefish and all of them detect it.

When I try to load any of the SDK sample plugins Carla shows an error which is the only hint I have about the problem: 

> Could not find the VST main entry in the plugin library

**Comment by scheffle** [comment]
Hi,
as long as I know, all of the hosts you stated are not supporting VST3. Please try with the demo version of Bitwig or Reaper.
