### ISSUE TITLE
Error Compiling in Linux 

### ISSUE THREAD

**Issue by nirban** [steinbergmedia/vst3sdk#44]
[ 17%] Built target vstgui
[ 18%] Building CXX object vstgui4/vstgui/uidescription/CMakeFiles/vstgui_uidescription.dir/editing/uieditmenucontroller.cpp.o
/home/nirban/JUCE/VST_SDK/VST3_SDK/vstgui4/vstgui/uidescription/editing/uieditmenucontroller.cpp: In instantiation of ‘VSTGUI::UIEditMenuController::getChildrenOfType(VSTGUI::CViewContainer*, VSTGUI::UTF8StringView, std::vector<VSTGUI::CView*>&) const::<lambda(auto:9)> [with auto:9 = VSTGUI::SharedPointer<VSTGUI::CView>]’:
/home/nirban/JUCE/VST_SDK/VST3_SDK/vstgui4/vstgui/uidescription/editing/../../lib/cviewcontainer.h:291:8:   required from ‘void VSTGUI::CViewContainer::forEachChild(Proc) const [with Proc = VSTGUI::UIEditMenuController::getChildrenOfType(VSTGUI::CViewContainer*, VSTGUI::UTF8StringView, std::vector<VSTGUI::CView*>&) const::<lambda(auto:9)>]’
/home/nirban/JUCE/VST_SDK/VST3_SDK/vstgui4/vstgui/uidescription/editing/uieditmenucontroller.cpp:729:3:   required from here
/home/nirban/JUCE/VST_SDK/VST3_SDK/vstgui4/vstgui/uidescription/editing/uieditmenucontroller.cpp:727:4: **error:** **cannot call member function ‘void VSTGUI::UIEditMenuController::getChildrenOfType(VSTGUI::CViewContainer*, VSTGUI::UTF8StringView, std::vector<VSTGUI::CView*>&) const’ without object
    getChildrenOfType (c, type, result);**
    ^
vstgui4/vstgui/uidescription/CMakeFiles/vstgui_uidescription.dir/build.make:494: recipe for target 'vstgui4/vstgui/uidescription/CMakeFiles/vstgui_uidescription.dir/editing/uieditmenucontroller.cpp.o' failed
make[2]: *** [vstgui4/vstgui/uidescription/CMakeFiles/vstgui_uidescription.dir/editing/uieditmenucontroller.cpp.o] Error 1
CMakeFiles/Makefile2:205: recipe for target 'vstgui4/vstgui/uidescription/CMakeFiles/vstgui_uidescription.dir/all' failed
make[1]: *** [vstgui4/vstgui/uidescription/CMakeFiles/vstgui_uidescription.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by scheffle** [comment]
Hi, please give us more information on your system. Which Linux distribution are you using and which compiler?

**Comment by nirban** [comment]
OS: Ubuntu 16.04
Compiler: g++
compiler version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by scheffle** [comment]
Hi, you need a newer compiler version. There should be a backport of gcc7 for Ubuntu 16.04 which should work with the SDK.

**Comment by nirban** [comment]
It worked with Ubuntu 18.04 
Thanks.
