### ISSUE TITLE
[Linux] compilation error

### ISSUE THREAD

**Issue by KottV** [steinbergmedia/vst3sdk#5]
Hi. I've got this error.
OpenSUSE TW gcc 7.2.1

> /home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.cpp: In member function ‘virtual bool Steinberg::Vst::AudioClient::process(Steinberg::Vst::IAudioClient::Buffers&, int64_t)’:
/home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.cpp:307:22: error: no matching function for call to ‘Steinberg::Vst::AudioClient::postprocess(Steinberg::Vst::IAudioClient::Buffers&)’
  postprocess (buffers);
                      ^
In file included from /home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.cpp:38:0:
/home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.h:105:7: note: candidate: void Steinberg::Vst::AudioClient::postprocess()
  void postprocess ();
       ^~~~~~~~~~~
/home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.h:105:7: note:   candidate expects 0 arguments, 1 provided
/home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.cpp: At global scope:
/home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.cpp:312:6: error: prototype for ‘void Steinberg::Vst::AudioClient::postprocess(Steinberg::Vst::IAudioClient::Buffers&)’ does not match any in class ‘Steinberg::Vst::AudioClient’
 void AudioClient::postprocess (Buffers& buffers)
      ^~~~~~~~~~~
In file included from /home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.cpp:38:0:
/home/kv/src/vst3sdk/public.sdk/samples/vst-hosting/audiohost/source/media/audioclient.h:105:7: error: candidate is: void Steinberg::Vst::AudioClient::postprocess()
  void postprocess ();
       ^~~~~~~~~~~

**Comment by ygrabit** [comment]
fixed in commit : 5c949aa86fe36697422c6b8a515776b941f1a5d0
