### ISSUE TITLE
"Valid State Transition" test always fails a 64-bit-only plugin

### ISSUE THREAD

**Issue by spinnylights** [steinbergmedia/vst3sdk#50]
In public.sdk/source/vst/testsuite/state/validstatetransition.cpp, at line 47, `ValidStateTransitionTest`'s constructor is declared as follows:

```cpp
ValidStateTransitionTest::ValidStateTransitionTest (ITestPlugProvider* plugProvider)
: TestEnh (plugProvider, kSample32)
{
}
```

Because sample size `kSample32` is specified there, `newsetup.symbolicSampleSize` is set to `kSample32` when calling the plugin's `setupProcessing` method. A 64-bit-only plugin should return `kResultFalse` in this case, as I understand it. However, the "Valid State Transition" test will always fail if the plugin returns `kResultFalse` from `setupProcessing`. Therefore, 64-bit-only plugins fail this test erroneously. What's more, the 64-bit state transition path for plugins with 32-bit and 64-bit support is never tested.

**Comment by ygrabit** [comment]
will be fixed in next update
