### ISSUE TITLE
Make the VST2 SDK available

### ISSUE THREAD

**Issue by egasimus** [steinbergmedia/vst3sdk#51]
Hi folks,

I'm trying to build the [Airwave](https://github.com/psycha0s/airwave/blob/1.3.3/CMakeLists.txt) VST bridge under NixOS. Currently, this requires a download of a 90MB archive and manual interference with NixOS's mostly automated build workflow just to fetch 136K of SDK code.

Would it possible to make the VST2 SDK available on GitHub as a separate repo? This would make certail users' lives a lot easier.

Cheers

**Comment by ygrabit** [comment]
VST2 SDK is not anymore supported.
https://www.steinberg.net/en/newsandevents/news/newsdetail/article/vst-2-coming-to-an-end-4727.html

**Comment by egasimus** [comment]
VST2 plugins are still out there and being used, including some old ones which will never be upgraded to VST3. Feel free to mark the old version as abandoned, unsupported and generally "not your problem", but what economic sense does it make to effectively destroy years of plugin developers' work by making new hosts unable to load old plugins? I understand that this is probably a business-motivated decision, but you folks should really do the right thing and preserve the v2 SDK's availability.

**Comment by egasimus** [comment]
I understand that, in our current neoliberal climate, large organisations such as Steinberg (or even the [BBC](http://www.ariadne.ac.uk/issue/36/tna/) for that matter) have difficulties accommodating issues of digital preservation, but the consensus in the software engineering community is that "old" platforms that don't make sense to maintain anymore are best left in the hands of the community of developers and creators who make use of them - not just erased from history as if they were suddenly worthless. Making technologies of historical interest such as VST2 available to the public would elevate Steinberg as a company that is a responsible steward to the software ecosystem that you have sparked.

**Comment by pepelevamp** [comment]
#1 rule of a platform is: don't change. in my view, as soon as your platform becomes used for other people to build things on - you should no longer have domain over it. applications yes, platforms no. no company can scale to accommodate the world.

**Comment by dromer** [comment]
It's not even an "platform", it's an API.

It's like saying browsers are not allowed to implement HTTP because we now have HTTP2.

**Comment by egasimus** [comment]
@dromer It's more like being _unable_ to implement HTTP because one morning someone at Google decides, "hey, the Internet is HTTP2-only as of today", and magically deletes all copies of the old API spec from the Internet. It's also similar to deprecating acoustic guitars in favour of going all-electric.

Since @steinbergmedia is probably not up to as much scrutiny as SV tech giants, and thus less likely to be as feedback-oriented, right now they can easily get away with such "magical" business decisions. After all, it's a proprietary ecosystem.

Given sufficient time, the community can reverse engineer anything, if nothing else out of spite against seeing another great product we grew up with get killed off. In the future, one would hope right-to-repair laws would cover cases like this, in the interest of digital preservation.

@steinbergmedia how soon until I need to maintain an extra PC with an old DAW to support the old VST2 plugins that take part in my signature sound? I don't know, maybe I'm not expected to be this consistent as an artist? Please release the VST2 spec and license it to the community, @steinbergmedia. If necessary, we'll provide our own implementation.

I also can't help but wonder if this is just another ripple of the win10/macos11 wave of deprecation, similar to the dumping of 1394 cards on the market once driver support was dropped for gear with perfectly fine converters.

**Comment by dromer** [comment]
@egasimus there is already a reverse engineered VST2 header since 2006 called VeSTige. It allows you to build a to-spec VST2 plugin.

It doesn't have any of the SDK features of course, but that's not really the point here (the SDK is probably the worst part about all of VST*, that and being completely closed to any revisions).

You can find examples of projects using vestige all over the place https://github.com/x42/lv2vst/blob/master/include/vestige.h

**Comment by egasimus** [comment]
@dromer Nice! Perhaps I should redirect my efforts to porting Airwave to use VeSTige.

**Comment by pepelevamp** [comment]
Yeah I didn't know anything about this either. Awesomeeeee

**Comment by anton-danielsson** [comment]
The HTTP vs HTTP2 argument is pretty solid.
Why not make the VST2 API definition available?

**Comment by dromer** [comment]
@anton-danielsson use `vestige.h` - done.

**Comment by Sophia-Cristina** [comment]
F-U, Steinberg, nobody liked what you guys did!
Absolutely no respect for you guys!

**Comment by aidanswank** [comment]
L Steinberg booooo !!!!!!!  tomatoes tomatoes tomatoes

**Comment by 0xdevalias** [comment]
They may try to erase it.. but the internet always remembers...

- https://web.archive.org/web/*/http://www.steinberg.net/sdk_downloads/*
  - [`vst_sdk2_3.zip`](https://web.archive.org/web/20150804090504/http://www.steinberg.net/sdk_downloads/vst_sdk2_3.zip)
  - [`vst_sdk2_4_rev2.zip`](https://web.archive.org/web/20161002042955/http://www.steinberg.net/sdk_downloads/vst_sdk2_4_rev2.zip)
  - [`vstsdk360_22_11_2013_build_100.zip`](https://web.archive.org/web/20231014014318*/http://www.steinberg.net/sdk_downloads/vstsdk360_22_11_2013_build_100.zip)
  - [`vstsdk365_28_08_2015_build_66.zip`](https://web.archive.org/web/20161220233834*/http://www.steinberg.net/sdk_downloads/vstsdk365_28_08_2015_build_66.zip)
  - [`vstsdk365_12_11_2015_build_67.zip`](https://web.archive.org/web/20200502121418*/http://www.steinberg.net/sdk_downloads/vstsdk365_12_11_2015_build_67.zip)
  - [`vstsdk366_21_06_2016_build_58.zip`](https://web.archive.org/web/20160703000636*/http://www.steinberg.net/sdk_downloads/vstsdk366_21_06_2016_build_58.zip)
  - [`vstsdk366_27_06_2016_build_61.zip`](https://web.archive.org/web/20220708155759*/https://www.steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip)
- https://github.com/search?type=code&q=%22Category++++%3A+VST+2.x+Interfaces%22+%22Filename++++%3A+pluginterfaces%2Fvst2.x%22
