### ISSUE TITLE
noteexpressionsynth example with non-VSTGUI gui?

### ISSUE THREAD

**Issue by jjYBdx4IL** [steinbergmedia/vst3sdk#54]
I'm looking for a decent (working) example of a VST synth plugin that is not using VSTGUI for its GUI. I'm probably going to try to strip down the existing example and remove the VSTGUI elements. However, I probably need ten times more time for that than someone who is actually "conversant" with that code base. Doesn't have to be nice looking, no rotating knobs or anything like that.

My final goal is to use Vulkan, especially because Apple dropped OpenGL support. But for that, I need a functional base without the UI config bloatware.

**Comment by ygrabit** [comment]
you´re welcome to propose some examples.
