### ISSUE TITLE
QWERTY should work like it did on VST2

### ISSUE THREAD

**Issue by K0rrid0r** [steinbergmedia/vst3sdk#56]
As of now VST3 most of the times cannot be played with the QWERTY keyboard, this is a big drawback for people who use the keyboard and design sound while modifying parameters.

It's about the keyboard focus. once the plugin is on focus, qwerty wont work. This 99% of the times worked with all VST2 plugins. 

This must be fixed asap.

**Comment by scheffle** [comment]
Can you please describe your issue in more detail?

**Comment by scheffle** [comment]
No feedback, closing this.
