### ISSUE TITLE
VST3 cannot be audible stopped by STOP on daw like a VST2 could.

### ISSUE THREAD

**Issue by K0rrid0r** [steinbergmedia/vst3sdk#57]
Yes. VST3 cannot be audible stopped by STOP on daw like any VST2 could, this is a problem if you are designing sounds with long decay and release and need to panic stop it to make changes or have quiet.

**Comment by scheffle** [comment]
What do you mean? Can you describe your issue in technical terms? Thanks you.

**Comment by scheffle** [comment]
No feedback, closing this.
