### ISSUE TITLE
MacOS install commands are incorrect

### ISSUE THREAD

**Issue by kmturley** [steinbergmedia/vst3sdk#58]
### 1) Incorrect folder command

Following the steps from the README.md:

```
mkdir build
cd build
cmake -GXcode ../vst3sdk
CMake Error: The source directory "/Sites/vst3sdk/vst3sdk" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

If you adjust the last command to:
`cmake -GXcode ../`

Then it works correctly!

Even better the command could be simplified to create the build folder automatically from the root:
```
cmake \
  -G "Xcode" \
  -S ./vst3sdk \
  -B ./build
cmake --build ./build --config Debug
```

### 2) Check correct dependency versions
It might also be worth including checking the version of cmake and xcode before installation:
```
cmake -version
xcodebuild -version
```

### 3) Clarify location of copy_vst2_to_vst3_sdk script
This script does not exist in the GitHub repository. And your README.md mentions:

> The VST2 SDK is not part anymore of the VST3 SDK, you have to use an older version of the SDK and copy the VST2_SDK folder into the VST_SDK folder. In order to build a VST2 version of the Plug-in and a VST3 at the same time, you need to copy the VST2 folder into the VST3 folder, simply run the following commands:

But it doesn't mention where to obtain the VST2 files and script. After some digging I found them at:
https://www.steinberg.net/vst3sdk

This is not a great solution though as it requires going to the site, and manually downloading a .zip file to get the required files.

Could you add the vst2sdk to github? e.g. make a repo here?
https://github.com/steinbergmedia/vst2sdk

Then plugin developers could add it as a git submodule .gitmodules file
```
[submodule "vst2sdk"]
  path = vst2sdk
  url = https://github.com/steinbergmedia/vst2sdk.git
[submodule "vst3sdk"]
  path = vst3sdk
  url = https://github.com/steinbergmedia/vst3sdk.git
```

This would allow automation of plugin development and builds!

**Comment by scheffle** [comment]
Hi,
thanks for the comments. We will adopt the documentation to make it more clear that "vst3sdk" is meant as a placeholder for the location where the sdk was checked out or downloaded to.
