### ISSUE TITLE
VST3PluginTestHost missing ?

### ISSUE THREAD

**Issue by MatthieuMv** [steinbergmedia/vst3sdk#62]
Hello !

I was wondering why the SDK repository don't contains the [VST3PluginTestHost](https://steinbergmedia.github.io/vst3_doc/vstsdk/applications.html?fbclid=IwAR0LC_Uuql2MHE1BGjAU_It0UGK9WNjvOKt34erRf1XKXhDOzHg2d0cApEE).

Maybe I just understood how to build / find it, could you help me please ?

Best regards,
Matthieu Moinvaziri

**Comment by ygrabit** [comment]
The VST3PluginTestHost is not open source code, that´s why we have included it only the full vesion of the SDK: check https://developer.steinberg.help/display/VST/VST+3+Links.
