### ISSUE TITLE
VST3SDK not including uidescription when building for Windows

### ISSUE THREAD

**Issue by simonhochrein** [steinbergmedia/vst3sdk#71]
Hello,

When I create a vst3sdk project on windows with default options and vstgui, I get a blank black screen on opening the plugin. After some investigation, I found that it was caused by a failure to load the uidescription file. I noticed that the uidescription file is not embedded into the vst unless "Create bundle for windows" is checked. However, if I use the windows bundle option the plugin is not detected by the DAW. Any suggestions?

**Comment by scheffle** [comment]
Which DAW? We are not aware of any host that cannot load packaged VST3 plug-ins (if the host supports VST3 in general).

**Comment by simonhochrein** [comment]
I'm currently using FL Studio 20, however the audio host sample failed to load the vst bundle as well.

**Comment by simonhochrein** [comment]
![image](https://user-images.githubusercontent.com/10032418/103484466-a30e2f80-4db4-11eb-93ed-2878f5870420.png)
This is what it looks like when I open the plugin (when I build non-bundled).

**Comment by scheffle** [comment]
As the bundle format is the default one, you should try to get that working. How are you trying to start the audio-host sample? What about the validator?

**Comment by simonhochrein** [comment]
The validator is successful. The editor host does load the bundle successfully. This could be a problem with FL Studio, then.

**Comment by scheffle** [comment]
Maybe an installation issue or path issue. Where's your plug-in located? Do you have a correct link to the common VST3 location?

**Comment by simonhochrein** [comment]
I believe I have found the issue. Symlinks do not work when the plugin is built as a bundle. I copied the bundle directly to the VST3 folder and it works as expected.

**Comment by simonhochrein** [comment]
My solution is replacing `COMMAND mklink` with `COMMAND mklink /D` on line 103 of cmake/modules/SMTG_AddSMTGLibrary.cmake

**Comment by scheffle** [comment]
Glad you fixed it. I will notify our Windows guru to check your solution.

**Comment by simonhochrein** [comment]
This might also affect Linux, it would be worth checking
