### ISSUE TITLE
VST2 SDK File(s) Missing?

### ISSUE THREAD

**Issue by zmand97** [steinbergmedia/vst3sdk#73]
A plugin from Github that I am working with (the GLSL Plugin) says that "The VST2 SDK can be obtained from the vstsdk3610_11_06_2018_build_37 (or older) VST3 SDK..." However, there seems to be no VST_2 in steinbergmedia / vst3dk's code, files, etc. Are they missing, or are they not supposed to be in there?

**Comment by ygrabit** [comment]
VST2 SDK is not anymore available.
