### ISSUE TITLE
HostingExample - editorhost error - dll does not export the required 'GetPluginFactory' function

### ISSUE THREAD

**Issue by RinoReyns** [steinbergmedia/vst3sdk#78]
I tried to run 'editorhost' example and I got an error "dll does not export the required 'GetPluginFactory' function. I didn't changed anything in the code, I just tried to run code from repo. Could anyone provide some hint to resolve this error?

**Comment by RinoReyns** [comment]
Okay, after debugging two of your samples I found small issues/uncheck corner cases/missing ReadMe for using this examples.
1) "editorhost" dosen't print "help" properly. For someone that is starting adventure with code it is a little bit confusing where to start. If you don't pass any vst plugin path it simply crashers with with error that I mentioned before. Root-cause: Simply there is wrong "if" statement in line 247 of "editorhost.cpp".
2) VST3Inspector also dosen't have any ReadMe how to use it. Inside of app there is hard coded assumption that plugin will be placed in given directory but it isn't written anywhere. Moreover, this sample also crushes when given directory is empty. Root-cause: in this case you are missing "if" statements in line 384-387 of "vst3sdk\public.sdk\samples\vst-hosting\inspectorapp\source\window.cpp" when you are assigning values from "modulePathList" and "modules"

**Comment by ygrabit** [comment]
Thanks for finding these, These will be fixed in next update
