### ISSUE TITLE
get error when editorhost debug in x86

### ISSUE THREAD

**Issue by simpleway2016** [steinbergmedia/vst3sdk#9]
I create x86 solution in vs2017 with command:
cmake.exe -G"Visual Studio 15 2017" ../vst3sdk
then i run project "editorhost"，it throw this exception
Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.

**Comment by simpleway2016** [comment]
i fixed this problem.
public.sdk\samples\vst-hosting\editorhost\source\platform\win32\window.h
modify code：
	using GetDpiForMonitorProc = HRESULT (*) (HMONITOR, MONITOR_DPI_TYPE, UINT*, UINT*);
	using SetProcessDpiAwarenessProc = HRESULT (*) (PROCESS_DPI_AWARENESS);
to：
	using GetDpiForMonitorProc = HRESULT (_stdcall *) (HMONITOR, MONITOR_DPI_TYPE, UINT*, UINT*);
	using SetProcessDpiAwarenessProc = HRESULT (_stdcall *) (PROCESS_DPI_AWARENESS);

**Comment by ygrabit** [comment]
will be included in next update. Thx
