### ISSUE TITLE
Error E0020 identifier "atomic_fetch_add" and "atomic_int_least32_t" is undefined (Win10)

### ISSUE THREAD

**Issue by lexlab245** [steinbergmedia/vst3sdk#90]
I get an error when trying to compile the examples. As I understand it, this error occurs at the compilation stage of the library "pluginterfaces" and i have no idea how to fix it. 
This is code that don't work (vst3sdk\pluginterfaces\base\funknown.cpp):
![image](https://user-images.githubusercontent.com/72731401/154833494-4180c73a-3bc6-436a-8b87-caae0a64d9bc.png)
This is the only error that occurs during compilation (except for errors that occur due to missing library that fails to compile due to those errors)

**Comment by LeStahL** [comment]
Set the C++ standard to 23 using

```
set(CMAKE_CXX_STANDARD 23)
```

Fixed it for me

**Comment by RinoReyns** [comment]
another option that I found somewhere in internet is following:
if (MSVC)
    set(SMTG_USE_STDATOMIC_H OFF CACHE BOOL "" FORCE)
endif()

I should be set in main Cmake file. Works for me. I use cxx_std_17.

**Comment by lexlab245** [comment]
The solution helped me: 
`cmake -DSMTG_USE_STDATOMIC_H=OFF .`

**Comment by seanbo** [comment]
> Set the C++ standard to 23 using
> 
> ```
> set(CMAKE_CXX_STANDARD 23)
> ```
> 
> Fixed it for me

This worked for me as well.  Thank you!!
