### ISSUE TITLE
no CMake SMTG_VST3_SDK file

### ISSUE THREAD

**Issue by pietro68** [steinbergmedia/vst3sdk#92]
Cloned repository, tried building for windows as specified, CMake stops saying:

CMake Error at CMakeLists.txt:19 (include):
  include could not find load file:

    SMTG_VST3_SDK

That file is nowhere to be found in my cloned repo.

**Comment by scheffle** [comment]
Did you clone with `git clone --recursive`

**Comment by dchmelik** [comment]
I downloaded a release tarball and have same problem.

**Comment by scheffle** [comment]
You have to use git. The release tarball feature in GitHub is of no use here.
