### ISSUE TITLE
cmake build error on mac [-Wunknown-warning-option]

### ISSUE THREAD

**Issue by mightgoyardstill** [steinbergmedia/vst3sdk#98]
current trying to run the cmake build option on mac right now and am getting the error:

warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'?
[-Wunknown-warning-option]

this is while trying to run the final step of building plugins and object files using the following command:

cmake --build . --config Release

(have also tried this without the --config Release flag)

heres what i get in my console:

[  0%] Building CXX object base/CMakeFiles/base.dir/source/baseiids.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  1%] Building CXX object base/CMakeFiles/base.dir/source/fbuffer.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  1%] Building CXX object base/CMakeFiles/base.dir/source/fdebug.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  1%] Building CXX object base/CMakeFiles/base.dir/source/fdynlib.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  1%] Building CXX object base/CMakeFiles/base.dir/source/fobject.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  1%] Building CXX object base/CMakeFiles/base.dir/source/fstreamer.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  2%] Building CXX object base/CMakeFiles/base.dir/source/fstring.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  2%] Building CXX object base/CMakeFiles/base.dir/source/timer.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  2%] Building CXX object base/CMakeFiles/base.dir/source/updatehandler.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  2%] Building CXX object base/CMakeFiles/base.dir/thread/source/fcondition.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  2%] Building CXX object base/CMakeFiles/base.dir/thread/source/flock.cpp.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
1 warning generated.
[  3%] Linking CXX static library ../lib/Debug/libbase.a
[  3%] Built target base
[  4%] Building CXX object VSTGUI.build/vstgui/lib/CMakeFiles/vstgui.dir/animation/animations.cpp.o
error: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Werror,-Wunknown-warning-option]
make[2]: *** [VSTGUI.build/vstgui/lib/CMakeFiles/vstgui.dir/animation/animations.cpp.o] Error 1
make[1]: *** [VSTGUI.build/vstgui/lib/CMakeFiles/vstgui.dir/all] Error 2
make: *** [all] Error 2

any suggestions? thinking this might be an issue with my clang compiler?

**Comment by scheffle** [comment]
Make sure to use a supported Xcode/Clang version. I think currently the oldest supported version is Xcode 10.1. I also recommended to use the Xcode generator: `cmake -GXcode`

**Comment by mightgoyardstill** [comment]
i’m not using xcode and would like to build it without creating the xcode projects, i'm compiling with Clang 12.0.0 x68_64-apple-darwin19.6.0

**Comment by scheffle** [comment]
It looks like that [this](https://github.com/steinbergmedia/vst3_cmake/blob/master/modules/SMTG_PlatformToolset.cmake#L53) line is wrong when not using Xcode on macOS. You can comment it out for now until it is fixed.

**Comment by mightgoyardstill** [comment]
thanks so much!
